# ---------------- #
#   Main Configs   #
# ---------------- #
baseurl:
url: http://blog.x1ah.me
date_format: "ordinal"
title: x1ah
subtitle: "x1ah"
description: "x1ah 的个人博客"
keywords: x1ah
timezone: Asia/Shanghai
encoding: "utf-8"
side_bar_repo_limit: 5

# ---------------- #
#      Author      #
# ---------------- #
author: x1ah
organization: xiachufang
organization_url: https://github.com/xiachufang
github_username: x1ah
location: Beijing, China
email: x1ahgxq@gmail.com

# ---------------- #
#    Navigation    #
# ---------------- #
navs:
  -
    href: /
    label: 首页

  -
    href: /categories/
    label: 分类

  -
    href: /wiki/
    label: 维基

  -
    href: /links/
    label: 链接

  -
    href: /about/
    label: 关于

# ---------------- #
#       RSS        #
# ---------------- #
subscribe_rss: /feed.xml

# ---------------- #
#      Jekyll      #
# ---------------- #
markdown: kramdown
kramdown:
    input: GFM
highlighter: rouge
paginate: 8
lsi: false
quiet: false
excerpt_separator: "\n\n"
permalink: /:year/:month/:day/:title/
gems:
    - jekyll-github-metadata
    - rouge
#     - jekyll-html-pipeline
    - jekyll-paginate
    - jekyll-sitemap
    - jekyll-feed
    - jemoji
#     - jekyll-mentions
collections:
    wiki:
        output: true
        permalink: /wiki/:path/

repository: x1ah/x1ah.github.io

# ---------------- #
#      Comments    #
# ---------------- #
# support provider: disqus, gitment, gitalk
comments_provider: disqus
# !!!重要!!! 请修改下面这些信息为你自己申请的
# !!!Important!!! Please modify infos below to yours
# https://disqus.com
disqus:
    username: x1ah-blog
# https://imsun.net/posts/gitment-introduction/
gitment:
    owner: x1ah
    repo: blog-comments
    oauth:
        client_id: xx
        client_secret: xx
# https://github.com/gitalk/gitalk#install
gitalk:
    owner: x1ah
    repo: blog-comments
    clientID: xx
    clientSecret: xx
# 在使用其它评论组件时可点击显示 Disqus
lazy_load_disqus : false

# ---------------- #
#      Search      #
# ---------------- #
simple_jekyll_search:
    # 是否支持全文搜索
    fulltext: false
    # 最多显示多少条搜索结果
    limit: 10

# ---------------- #
#    Analytics     #
# ---------------- #
google:
    analytics_id: UA-86118909-1
